spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fortium?createDatabaseIfNotExist=true
    password: 1234
    username: root

  jpa:
    hibernate:
      ddl-auto: update

jwt-key: HpU9jymOYKQK6UzxqTqD0c5lDL8ACRYqA7fdIQyLZzU= # This key is open for the demonstration purpose of this selection test only!